### ISSUE TITLE
[feature-ral] Test with a CB3 UR5: UR: invalid package

### ISSUE THREAD

**Issue by liushuya7** [jhu-saw/sawUniversalRobot#7]
I have tried to connect to a UR5. This is the first error I encountered:

```bash
$ ros2 run universal_robot universal_robot -i 10.176.186.151
Options provided:
 - IP address for the UR controller [10.176.186.151]

File: mtsUniversalRobotScriptRT.cpp Line: 310 -  need to add joint configuration with names, type and maybe limits?  Can we retrieve these via API?
-W Class mtsUniversalRobotScriptRT: ReadPolyscopeVersion: version = 3.15.8
-W Class mtsUniversalRobotScriptRT: Found new version, packet length = 1220, polyscope version = 3.15.8
-E Class mtsUniversalRobotScriptRT: UR:control: 1.7093e+09s, #1: UR: invalid package
[INFO] [1709303948.847089887] [rclcpp]: 1709303948.746065s, #1: UR: socket connected, IP: 10.176.186.151
[INFO] [1709303948.847184597] [rclcpp]: 1709303948.746337s, #2: UR-DashboardServer: Connected: Universal Robots Dashboard Server
[ERROR] [1709303948.847197407] [rclcpp]: 1709303948.846896s, #1: UR: invalid package
```

![image](https://github.com/jhu-saw/sawUniversalRobot/assets/6867028/837720fb-8b03-49e5-ae8c-18da79ed595e)

**Comment by pkazanzides** [comment]
Which branch are you using?  Support for CB3 (packet length of 1220) was added last summer in the `devel` branch, which is also in the `feature-ral` branch.

**Comment by pkazanzides** [comment]
Actually, I see the problem.  Your Polyscope major version is "3", which seems a bit old for CB3.  The code currently assumes that CB3 uses Polyscope major version "5".  What type of robot are you using?  Is it an e-series?

**Comment by liushuya7** [comment]
I was using `feature-ral` branch. I was testing it on CB3 URSim and it didn't work. I think you are right. I just tested it on UR10e, and it works!

![image](https://github.com/jhu-saw/sawUniversalRobot/assets/6867028/60d93766-a024-4536-afe8-4a19e0375a54)

**Comment by pkazanzides** [comment]
O.K.  Good to know.  The current implementation is intended to be able to handle new interface versions for both CB2 and CB3 controllers, which is why it also checks the Polyscope version.  If we can assume that there will not be any new CB2 versions, we could change the implementation so that it would have worked for this configuration.  I'm going to close this issue for now.
